version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    depends_on:
      - 'postgres'
    build: .
    env_file:
      - '.env'
    ports:
      - '8080:8080'
    volumes:
      - '.:/go/src/app'

volumes:
  postgres: {}
